spring:
  application:
    name: performance
  datasource:
    url: jdbc:postgresql://localhost:5432/performance
    username: dekan
    password: s3cret
    driver-class-name: org.postgresql.Driver
    hikari: # for external
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false # for hello
    properties: # Find Performance Issues # Generate and log statistics
      hibernate:
        generate_statistics: true
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE


decorator:
  datasource:
    flexy-pool:
      threshold:
        connection:
          lease: 0
          acquire: -1

logging:
  level:
    org:
      hibernate:
        stat: DEBUG
        sql: DEBUG
        cache: DEBUG
