spring:
  application:
    name: performance
  datasource:
    url: jdbc:postgresql://localhost:5432/performance
    username: dekan
    password: s3cret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

decorator:
  datasource:
    flexy-pool:
      threshold:
        connection:
          lease: 0
          acquire: -1